# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-26 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=b'', verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe8\xaf\xa6\xe6\x83\x85')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8bc4\u8bba',
                'verbose_name_plural': '\u7528\u6237\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=b'\xe7\x94\xb5\xe5\xbd\xb1\xe6\xa0\x87\xe9\xa2\x98')),
                ('url', models.CharField(max_length=300, verbose_name=b'\xe7\x94\xb5\xe5\xbd\xb1\xe5\x9c\xb0\xe5\x9d\x80')),
                ('info', models.TextField(default=b'', verbose_name=b'\xe7\x94\xb5\xe5\xbd\xb1\xe7\xae\x80\xe4\xbb\x8b')),
                ('logo', models.ImageField(default=b'image/default.png', upload_to=b'image/%Y/%m', verbose_name=b'\xe5\xb0\x81\xe9\x9d\xa2')),
                ('star', models.IntegerField(max_length=11, verbose_name=b'\xe6\x98\x9f\xe7\xba\xa7')),
                ('play_nums', models.IntegerField(max_length=11, verbose_name=b'\xe6\x92\xad\xe6\x94\xbe\xe9\x87\x8f')),
                ('comment_nums', models.IntegerField(max_length=11, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0')),
                ('area', models.CharField(max_length=200, verbose_name=b'\xe4\xb8\x8a\xe6\x98\xa0\xe5\x9c\xb0\xe5\x8c\xba')),
                ('release_time', models.DateField(default=datetime.datetime.now, verbose_name=b'\xe4\xb8\x8a\xe6\x98\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('length', models.CharField(max_length=200, verbose_name=b'\xe6\x97\xb6\xe9\x95\xbf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u7535\u5f71\u4fe1\u606f',
                'verbose_name_plural': '\u7535\u5f71\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='MovieCol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Movie', verbose_name=b'\xe7\x94\xb5\xe5\xbd\xb1')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=b'\xe7\x94\xb5\xe5\xbd\xb1\xe6\xa0\x87\xe9\xa2\x98')),
                ('logo', models.ImageField(default=b'image/default.png', upload_to=b'image/%Y/%m', verbose_name=b'\xe5\xb0\x81\xe9\x9d\xa2')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u4e0a\u6620\u9884\u544a',
                'verbose_name_plural': '\u4e0a\u6620\u9884\u544a',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
    ]
