# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20180526_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.AddField(
            model_name='movie',
            name='download_url',
            field=models.CharField(default=b'', max_length=300, verbose_name=b'\xe4\xb8\x8b\xe8\xbd\xbd\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(default=b'videos/default.mp4', max_length=200, upload_to=b'videos/%Y/%m', verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\x96\x87\xe4\xbb\xb6'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comment_nums',
            field=models.IntegerField(verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='play_nums',
            field=models.IntegerField(verbose_name=b'\xe6\x92\xad\xe6\x94\xbe\xe9\x87\x8f'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.IntegerField(verbose_name=b'\xe6\x98\x9f\xe7\xba\xa7'),
        ),
    ]
